samples: "resources/samples.tsv"
  # short_reads: "resources/samples_short.tsv"
  # long_reads: "resources/samples_long.tsv"
regular_expression: "[^/]+" #Sample IDs should match the long and short reads. 

hybrid_assembly: "yes" # "yes"/"no", 

# parameters:
skip_trimming: 'True'
skip_fastQC: 'True'
skip_qualimap: 'True'

# QC
fastqc:
  extra: ""

multiqc:
  extra: ""

trimmomatic:
  extra: "" # user can add any string 

unicycler:
  extra: "" #https://github.com/rrwick/Unicycler#method-hybrid-assembly