#DIRECTORIES 
samples: "resources/samples.tsv"
regular_expression: "[^/]+" #Sample IDs should match the long and short reads. 
contamination_reference:
  long: "resources/references/contamination_long.fasta"
  short: "resources/references/contamination_short.fasta"
  # short_reads: "resources/samples_short.tsv"
  # long_reads: "resources/samples_long.tsv"


#OPTIONAL STEPS
#Optional workflow steps can be set to "True" or "False" each 
#Preprocessing 
trimming: 
  long: 'False'
  short: 'False'
screening: 
  long: 'False'
  short: 'True'   
decontamination: 
  long: "False"
  short: "False"
qc:
  long: 'False'
  short: 'False'
#Assembly 
hybrid_assembly: "True" 
#Analysis 
mlst: 'False'
resistance: 'False'
virulence: 'False'
plasmids: 'False'


#PARAMETERS
#Paremeters. Set to the default used in our pipeline. 
#In extra any string can be provided.  A link is given to the manual of the respective tool. 
fastqc:
  extra: ""

longqc:
  preset: ont-rapid  # what comes after -x
  extra: ""

multiqc:
  extra: ""

trimmomatic_short:
  trailing: 20
  illuminaclip:
    file: "resources/adapters/TruSeq3-PE.fa"
    seedMissmatches: '2'
    palindromeClipThreshold: '30'
    simpleClipThreshold: '10'
  extra: "" 

trimmomatic_ONT:
trailing: 20
extra: ""

unicycler:
  extra: "" #https://github.com/rrwick/Unicycler#method-hybrid-assembly

kraken: 
  database: "resources/kraken_db" #directory to the kraken database used for screening. 
  quick: "True" #https://github.com/DerrickWood/kraken2/wiki/Manual

tree:
  method: "iqtree" #{fasttree,raxml,iqtree}