samples:
  short-reads: "resources/samples_short.tsv"
  long-reads: ""


# QC
fastqc:
  extra: ""

longqc:
  preset: ont-rapid  # what comes after -x
  extra: ""

multiqc:
  extra: ""

trimmomatic_short:
  trailing: 20
  illuminaclip:
    file: "resources/adapters/TruSeq3-PE.fa"
    seedMissmatches: '2'
    palindromeClipThreshold: '30'
    simpleClipThreshold: '10'
  extra: "" 

trimmomatic_ONT:
trailing: 20
extra: ""

