#DIRECTORIES 
#-----------------
samples: "resources/samples.tsv"
contamination_reference:
  long: "" #Should be provided if decontamination-long is set to True, and can be created based on the screening results.  
  short: "" #Should be provided if decontamination-short is set to True, and can be created based on the screening results.   
virulence_database: "" #If virulence is set to True but no path is provided, the VF core DNA database will be downloaded and build automatically. 
plasmids_database: ""  #If plasmids is set to True but no path is provided, the PLSD database will be downloaded and build automatically. 
resistance_database: "" 
blacklist: "" #Add file path here. A blacklist can optionally be provided to mask certain samples for the phylogenetic inference # # "resources/blacklist.txt" provided as an example


#OPTIONAL STEPS
#-----------------
#Optional workflow steps can be set to "True" or "False" each 
#Preprocessing 
trimming: 
  long: 'False'
  short: 'False'
screening: 
  long: 'False'
  short: 'False'   
decontamination: 
  long: "False" 
  short: "False"
qc:
  long: 'False'
  short: 'False'
#Assembly 
hybrid_assembly: "True" 
busco: "True"
#Analysis 
mlst: 'True'
resistance: 'True'
virulence: 'True'
plasmids: 'True'
#Phylogeny
roary_plots: 'True'


#PARAMETERS
#-----------------
#Paremeters. Set to the default used in our pipeline. 
#In extra any string can be provided.  A link is given to the manual of the respective tool. 
fastqc:
  extra: ""                                     #https://hbctraining.github.io/Intro-to-rnaseq-hpc-salmon-flipped/lessons/06_qc_running_fastqc_sbatch.html
longqc: 
  preset: ont-rapid                             #Specifies a platform/kit to be evaluated {pb-rs2, pb-sequel, ont-ligation, ont-rapid, ont-1dsq}
  extra: ""                                     #https://github.com/yfukasawa/LongQC
multiqc:
  extra: ""                                     #https://github.com/ewels/MultiQC
trimmomatic:
  trailing: 20                                  #Specifies the minimum quality required to keep a base.
  illuminaclip:
    file: ""    #Path to the adapters, should be provided if trimming for short reads is set to true. 
    seedMissmatches: '2' #Specifies the maximum mismatch count which will still allow a full match to be performed
    palindromeClipThreshold: '30' #Specifies how accurate the match between the two 'adapter ligated' reads must be for PE palindrome read alignment.
    simpleClipThreshold: '10' #Specifies how accurate the match between any adapter etc. sequence must be against a read.
  extra: ""  #https://github.com/usadellab/Trimmomatic
porechop:
  extra: "" #https://github.com/rrwick/Porechop
unicycler:
  extra: "" #https://github.com/rrwick/Unicycler#method-hybrid-assembly
kraken: 
  database: "" #If screening for either long or short reads is set to true, a Kraken database should be provided here. 
  quick: "True" #https://github.com/DerrickWood/kraken2/wiki/Manual
tree:
  extra: "" #https://sanger-pathogens.github.io/Roary/  # FastTree command (3rd step in Roary's recipe)
quast:
  extra: "" #https://github.com/ablab/quast
busco_params: #If BUSCO is set to true: if specified path to BUSCO lineage local file, prevent BUSCO searching online with offline: "True"
  lineage: "enterobacterales_odb10" # Path to lineage directory OR lineage name when offline: "False"
  offline: "False" 
  extra: "" #https://github.com/metashot/busco
rgi:
  extra: "" #https://github.com/arpcard/rgi#using-rgi-main-genomes-genome-assemblies-metagenomic-contigs-or-proteomes
blastn:
  eval: 0.000005 # E-value threshold used to prune the results after doing the blast search. 
  extra: "" #https://www.ncbi.nlm.nih.gov/books/NBK569856/
prokka:
  extra: "" #https://github.com/tseemann/prokka 
roary: 
  percentage_threshold: "95" #percentage of isolates a gene must be in to be core
  extra: "" #https://sanger-pathogens.github.io/Roary/
plot_roary:
  extra: "" # roary's additional visualization script;    https://github.com/sanger-pathogens/Roary/tree/master/contrib/roary_plots 

